#ifndef MLK_SVE2_SME_CONFIG_REF_H
#define MLK_SVE2_SME_CONFIG_REF_H

#ifndef MLK_CONFIG_PARAMETER_SET
#define MLK_CONFIG_PARAMETER_SET 768
#endif

#define MLK_CONFIG_NAMESPACE_PREFIX mlkem_sve2_sme
#define MLK_CONFIG_NO_RANDOMIZED_API
#define MLK_CONFIG_FIPS202_CUSTOM_HEADER "mlkem_fips202_glue.h"
#define MLK_CONFIG_FIPS202X4_CUSTOM_HEADER "mlkem_fips202x4_glue.h"

#endif
